const express = require("express");
const router = express.Router();
const createTask = require("./createTask");
const Task = require("../../models/tasksSchema");
const { updateTask, errorUpdate } = require("./updateTask");
const deleteTask = require("./deleteTask");
const { findAllTasks, findTaskById } = require("./findTask");
const errorCatcher = require("./errorMiddleware");
router.post("/", createTask(Task));
router.put("/:id", errorUpdate(Task), updateTask(Task));
router.patch("/:id", errorUpdate(Task), updateTask(Task));
router.delete("/:id", deleteTask(Task));
router.get("/", findAllTasks(Task));
router.get("/:id", findTaskById(Task));
router.use(errorCatcher);
module.exports = router;
