const express = require("express");
const router = express.Router();
const createTask = require("./createTask");
const Task = require("../../models/tasksSchema");
const { updateTask } = require("./updateTask");
const deleteTask = require("./deleteTask");
const { findAllTasks, findTaskById } = require("./findTask");
const errorCatcher = require("../../middleware/todos/errorMiddleware");
router.post("/", createTask);
router.put("/:id", updateTask);
router.patch("/:id", updateTask);
router.delete("/:id", deleteTask);
router.get("/", findAllTasks);
router.get("/:id", findTaskById);
router.use(errorCatcher);
module.exports = router;
