const express = require('express')
const router = express.Router()
const errorCatcher = require('../../middleware/errorMiddleware')
const asyncHandler = require('../../libraries/asyncHandler')
router.post('/', asyncHandler(require('./create')))
router.put('/:id', asyncHandler(require('./update')))
router.patch('/:id', asyncHandler(require('./update')))
router.delete('/:id', asyncHandler(require('./delete')))
router.get('/', asyncHandler(require('./tasks')))
router.get('/:id', asyncHandler(require('./show')))
router.use(errorCatcher)
module.exports = router
